# -*- coding: utf-8 -*-
"""OOP2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zhoOkszD-4gsEzI-PvHs-Ayg11pQasI9
"""

import random
class bankAccount:
  def __init__(self,name,initial_money_account):
    self.name=name
    self.initial_money_account=initial_money_account
    self.uniqe_id= random.randint(1000,999999)
    self.account_balance=initial_money_account

  def depositing_money(self):
    new_deposit= float(input("please enter the new deposit:"))
    self.account_balance= self.initial_money_account +new_deposit
    print(f"the amount of money is {self.account_balance}")

  def withdrawing(self):
    amount_of_withdrawing= float(input("please enter the amount of withdrowing:"))
    if self.account_balance <= amount_of_withdrawing :
      self.account_balance = (self.initial_money_account) - (amount_of_withdrawing)
      print(f"it is done and your new account balance is : {self.account_balance}")
    else:
      print("your money is insufficient")

  def display_info(self):
    print(f"the account holder is :{self.name} with ID_number: {self.uniqe_id}")
    print(f"the account balance is : {self.account_balance}")


first_costumer = bankAccount("Ali",1000)
first_costumer.depositing_money()
first_costumer.withdrawing()
first_costumer.display_info()